const data = {
  rent: [
    {
      id: 1,
      slug: 'house1',
      name: "Malto house",
      price: 250000,
      type: "Вилла",
      bedroom: 4,
      bathroom: 6,
      district: 'Бонг Тао',
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
    {
      id: 2,
      slug: 'house2',
      name: "Malto house",
      price: 350000,
      type: "Бунгало",
      bedroom: 2,
      bathroom: 6,
      district: 'Бонг Тао',
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
    {
      id: 3,
      slug: 'house3',
      name: "Malto house",
      price: 450000,
      type: "Вилла",
      bedroom: 2,
      district: 'Бонг Тао',
      bathroom: 4,
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
    {
      id: 4,
      slug: 'house4',
      name: "Malto house",
      price: 550000,
      district: 'Бонг Тао',
      type: "Дом",
      bedroom: 6,
      bathroom: 2,
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
    {
      id: 5,
      slug: 'house5',
      name: "Malto house",
      price: 450000,
      type: "Вилла",
      bedroom: 6,
      district: 'Бонг Тао',
      bathroom: 4,
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
    {
      id: 6,
      slug: 'house6',
      name: "Malto house",
      price: 950000,
      type: "Вилла",
      district: 'Бонг Тао',
      bedroom: 6,
      bathroom: 6,
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
    {
      id: 7,
      slug: 'house7',
      name: "Malto house",
      price: 150000,
      district: 'Бонг Тао',
      type: "Вилла",
      bedroom: 2,
      bathroom: 4,
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
    {
      id: 8,
      slug: 'house8',
      name: "Malto house",
      price: "480 000",
      district: 'Бонг Тао',
      type: "Вилла",
      bedroom: 4,
      bathroom: 2,
      category: 'rent',
      table: ['Malto house', 'Банг Тао', 'Вилла', '2323232', '10 минут пешком', 'Год', '4', '4', '10 минут', 'Да', 'Море, город'],
    },
  ],
  purchase: [
    {
      id: "1",
      slug: 'villa1',
      name: "Malto house",
      price: "111 111",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
    {
      id: "2",
      slug: 'villa2',
      name: "Malto house",
      price: "350 000",
      type: "Бунгало",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
    {
      id: "3",
      slug: 'villa3',
      name: "Malto house",
      price: "450 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
    {
      id: "4",
      slug: 'villa4',
      name: "Malto house",
      price: "550 000",
      type: "Дом",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
    {
      id: "5",
      slug: 'villa5',
      name: "Malto house",
      price: "450 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
    {
      id: "6",
      slug: 'villa6',
      name: "Malto house",
      price: "950 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
    {
      id: "7",
      slug: 'villa7',
      name: "Malto house",
      price: "150 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
    {
      id: "8",
      slug: 'villa8',
      name: "Malto house",
      price: "480 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
      table: ['Активно', 'Банг Тао', '2323232', '11.11.2011', '220 м2', '4', '4', 'Дом, бассейн, сад, гараж', 'Ежемесячно', 'Привелегии', 'Вилла', 'Море, город'],
    },
  ],
  service: [
    {
      id: "1",
      slug: 'transfer1',
      name: "Трансфер",
      price: "1 500",
      type: "Услуга",
      category: 'service',
    },
    {
      id: "2",
      slug: 'transfer2',
      name: "Трансфер",
      price: "10 000",
      type: "Услуга",
      category: 'service',
    },
    {
      id: "3",
      slug: 'transfer3',
      name: "Трансфер",
      price: "7 500",
      type: "Услуга",
      category: 'service',
    },
  ],
};

export default data;