const data = {
  rent: [
    {
      id: "1",
      slug: 'house1',
      name: "Malto house",
      price: "250 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
    {
      id: "2",
      slug: 'house2',
      name: "Malto house",
      price: "350 000",
      type: "Бунгало",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
    {
      id: "3",
      slug: 'house3',
      name: "Malto house",
      price: "450 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
    {
      id: "4",
      slug: 'house4',
      name: "Malto house",
      price: "550 000",
      type: "Дом",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
    {
      id: "5",
      slug: 'house5',
      name: "Malto house",
      price: "450 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
    {
      id: "6",
      slug: 'house6',
      name: "Malto house",
      price: "950 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
    {
      id: "7",
      slug: 'house7',
      name: "Malto house",
      price: "150 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
    {
      id: "8",
      slug: 'house8',
      name: "Malto house",
      price: "480 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'rent',
    },
  ],
  purchase: [
    {
      id: "1",
      slug: 'villa1',
      name: "Malto house",
      price: "111 111",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
    {
      id: "2",
      slug: 'villa2',
      name: "Malto house",
      price: "350 000",
      type: "Бунгало",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
    {
      id: "3",
      slug: 'villa3',
      name: "Malto house",
      price: "450 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
    {
      id: "4",
      slug: 'villa4',
      name: "Malto house",
      price: "550 000",
      type: "Дом",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
    {
      id: "5",
      slug: 'villa5',
      name: "Malto house",
      price: "450 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
    {
      id: "6",
      slug: 'villa6',
      name: "Malto house",
      price: "950 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
    {
      id: "7",
      slug: 'villa7',
      name: "Malto house",
      price: "150 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
    {
      id: "8",
      slug: 'villa8',
      name: "Malto house",
      price: "480 000",
      type: "Вилла",
      bedroom: '4',
      bathroom: '2',
      category: 'purchase',
    },
  ],
  service: [
    {
      id: "1",
      slug: 'transfer1',
      name: "Трансфер",
      price: "1 500",
      type: "Услуга",
      category: 'service',
    },
    {
      id: "2",
      slug: 'transfer2',
      name: "Трансфер",
      price: "10 000",
      type: "Услуга",
      category: 'service',
    },
    {
      id: "3",
      slug: 'transfer3',
      name: "Трансфер",
      price: "7 500",
      type: "Услуга",
      category: 'service',
    },
  ],
};

export default data;